<?php

require_once('custom/tests/SugarTestSupportUtilities.php');

class SugarTestSupportUserUtilities extends SugarTestSupportUtilities
{
    protected $_beanName = 'Users';

    public function __construct()
    {
        parent::__construct();
    }

    public function create($attributes = array(), $defaults= array())
    {
        if (isset($_REQUEST['action'])) {
            unset($_REQUEST['action']);
        }

        $time = mt_rand();
        $userId = 'SugarUser';

        //set defaults
        $coreDefaults = array(
            'is_admin' => 0,
            'user_name' => $userId . $time,
            'user_hash' => md5($userId . $time),
            'first_name' => $userId,
            'last_name' => $time,
            'status' => 'Active',
            'is_group' => 0,
            'portal_only' => 0,
            'default_team' => '1',
            'team_id' => '1',
        );

        $defaults = $this->merge($defaults, $coreDefaults);

        $bean = parent::create($attributes, $defaults);
        $bean->fill_in_additional_detail_fields();

        return $bean;
    }

    public function deleteAll()
    {
        parent::deleteAll(); // TODO: Change the autogenerated stub
        $ids = $this->getCreatedIds();
        if (count($ids) > 0) {
            $in = "'" . implode("', '", $ids) . "'";
            $GLOBALS['db']->query("DELETE FROM user_preferences WHERE assigned_user_id IN ({$in})");
            $GLOBALS['db']->query("DELETE FROM teams WHERE associated_user_id IN ({$in})");
            $GLOBALS['db']->query("DELETE FROM team_memberships WHERE user_id IN ({$in})");
            // delete any created email address rows
            //$GLOBALS['db']->query("DELETE FROM email_addresses WHERE id IN (SELECT DISTINCT email_address_id FROM email_addr_bean_rel WHERE bean_module ='Users' AND bean_id IN ({$in}))");
            //$GLOBALS['db']->query("DELETE FROM emails_beans WHERE bean_module='Users' AND bean_id IN ({$in})");
            //$GLOBALS['db']->query("DELETE FROM email_addr_bean_rel WHERE bean_module='Users' AND bean_id IN ({$in})");
        }
    }
}
