<?php

require_once('custom/tests/SugarTestSupportUtilities.php');

class SugarTestSupportTeamsUtilities extends SugarTestSupportUtilities
{
    protected $_beanName = 'ACLRoles';

    public function __construct()
    {
        parent::__construct();
    }

    public function create($attributes = array(), $defaults= array())
    {
        //set defaults
        $coreDefaults = array(
        //    "enabled" => true,
        );

        $defaults = $this->merge($defaults, $coreDefaults);

        $bean = parent::create($attributes, $defaults);
        return $bean;
    }

    public function deleteAll()
    {
        parent::deleteAll(); // TODO: Change the autogenerated stub
        $ids = $this->getCreatedIds();
        if (count($ids) > 0) {
            $in = "'" . implode("', '", $ids) . "'";
            $GLOBALS['db']->query("DELETE FROM team_sets_team WHERE team_id IN ({$in})");
        }
    }
}
